<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="102" started-at="2019-08-27T14:07:49Z" finished-at="2019-08-27T14:07:49Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="102" started-at="2019-08-27T14:07:49Z" finished-at="2019-08-27T14:07:49Z">
      <class name="com.Test.LoginTest">
        <test-method status="FAIL" signature="setUp()[pri:0, instance:com.Test.LoginTest@39ba5a14]" name="setUp" is-config="true" duration-ms="0" started-at="2019-08-27T19:37:02Z" finished-at="2019-08-27T19:37:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.Base.BaseSetUp.setUp(BaseSetUp.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="verifyLoginFunctionality()[pri:0, instance:com.Test.LoginTest@39ba5a14]" name="verifyLoginFunctionality" duration-ms="1" started-at="2019-08-27T19:37:49Z" finished-at="2019-08-27T19:37:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginFunctionality -->
        <test-method status="SKIP" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.Test.LoginTest@39ba5a14]" name="getResult" is-config="true" duration-ms="0" started-at="2019-08-27T19:37:49Z" finished-at="2019-08-27T19:37:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="SKIP" signature="endReport()[pri:0, instance:com.Test.LoginTest@39ba5a14]" name="endReport" is-config="true" duration-ms="0" started-at="2019-08-27T19:37:49Z" finished-at="2019-08-27T19:37:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- com.Test.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
